# Location Params
FROM_FOLDER: '../../data/train/'
TO_FOLDER: '../../data/intermediate1/'
DF_PATH: '../../data/transformation_split.csv'

IS_OS_WINDOWS: False
# Transformation Params
## Current IMage size
IMAGE_SIZE: 500 
## Get rid of black boarder around the image
REDUCE_PIXEL_CROP: 120 
## Resize on this size
RESIZE: 256
## Number of transforms in sequence
RANDOM_APPLY_N: 2
RANDOM_REPLACE: False
RANDOM_REUSE_TRANSFORM: False

# Multiprocessing parmas
GIVEN_KEY: False
N_PROCESSES: 5

# Set test Parameter
TEST_ONLY: False
