# Location Params
FROM_FOLDER: '../../data/images_transformed'
TO_FOLDER: '../../data/prepared_images'

# Transformation Params
IMAGE_SIZE: 500
REDUCE_PIXEL_CROP: 120
RESIZE: 128
RANDOM_APPLY_N: 2
RANDOM_REPLACE: False
RANDOM_REUSE_TRANSFORM: False

# Multiprocessing parmas
N_PROCESSES: 4
TEST_ONLY: False