# Location Params
FROM_FOLDER: '../../data/images_transformed'
TO_FOLDER: '../../data/prepared_images/'
DF_PATH_FROM: '../../data/transformation_split.csv'
#DF_PATH_TO: '../../data/split_prepared_images.csv'

# Transformation Params
## Current IMage size
IMAGE_SIZE: 500 
## Get rid of black boarder around the image
REDUCE_PIXEL_CROP: 120 
## Resize on this size
RESIZE: 128
## Number of transforms in sequence
RANDOM_APPLY_N: 2
RANDOM_REPLACE: False
RANDOM_REUSE_TRANSFORM: False

# Multiprocessing parmas
N_PROCESSES: 4
TEST_ONLY: False